ColombraroConfig/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('ColombraroLogin.urls')),
    path('erp/', include('ColombraroERP.urls')),
    path('reports/', include('ColombraroReports.urls')),
    path('user/', include('ColombraroUser.urls')),
    path('admin/', admin.site.urls),
]
# Ruta para cargar archivos img
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ColombraroERP/urls.py
from django.urls import path
from .views.dashboard.views import DashboardView
from .views.category.views import *
from .views.product.views import *
from .views.client.views import *
from .views.sale.views import *
from .views.tests.views import TestView

app_name = 'erp'
urlpatterns = [
    # ---------- DASHBOARD / PANEL DE ADMINISTRADOR ----------
    path('home/', DashboardView.as_view(), name='dashboard'),
    # ----------- CATEGORÍA / CATEGORY ----------------------
    path('category/list/', CategoryListView.as_view(), name='category_list'),
    path('category/detail/<int:pk>/',
         CategoryDetailView.as_view(), name='category_detail'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/',
         CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/',
         CategoryDeleteView.as_view(), name='category_delete'),
    # ------------ PRODUCT / PRODUCTO ----------------------------
    path('product/list/', ProductListView.as_view(), name='product_list'),
    path('product/detail/<int:pk>/',
         ProductDetailView.as_view(), name='product_detail'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/',
         ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/',
         ProductDeleteView.as_view(), name='product_delete'),
    # ------------ CLIENT / CLIENTES ----------------------------
    path('client/list/', ClientListView.as_view(), name='client_list'),
    path('client/detail/<int:pk>/',
         ClientDetailView.as_view(), name='client_detail'),
    path('client/create/', ClientCreateView.as_view(), name='client_create'),
    path('client/update/<int:pk>/',
         ClientUpdateView.as_view(), name='client_update'),
    path('client/delete/<int:pk>/',
         ClientDeleteView.as_view(), name='client_delete'),
    # ------------ SALE / VENTAS ----------------------------
    path('sale/list/', SaleListView.as_view(), name='sale_list'),
    path('sale/create/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/invoice/pdf/<int:pk>/',
         SaleInvoicePdfView.as_view(), name='sale_invoice_pdf'),
    # ------------ TESTS  ------------------------------------
    path('test/', TestView.as_view(), name="test"),
]

ColombraroReports/urls.py
from django.urls import path
from .views import ReportSaleView

app_name = 'reports'
urlpatterns = [
    # ---------- REPORTES de VENTAS / REPORTS SALE ----------
    path('sale/', ReportSaleView.as_view(), name='reports_sale'),
]

ColombraroUser/urls.py
from django.urls import path
from ColombraroUser.views import *

app_name = 'user'

urlpatterns = [
    path('list/', UserListView.as_view(), name='user_list'),
    path('create/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('detail/<int:pk>/', UserDetailView.as_view(), name='user_detail'),
]

ProyectoColombraro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('erp/', include('ColombraroERP.urls'))
]

ColombraroERP/views/category/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.http import JsonResponse
# Decoradores
from django.views.decorators.csrf import csrf_exempt
# Mixines
from ColombraroERP.mixins import IsSuperUserMixins, ValidatePermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
#  Clases Genericas
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
# Categorias
from ColombraroERP.models import Categorias
from ColombraroERP.forms import CategoriasForm


class CategoryListView(LoginRequiredMixin, ListView):
    model = Categorias
    template_name = 'pages/category/category_list.html'

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Categorias.objects.all():
                    data.append(i.toJSON())
            else:
                data['error'] = 'Se produjo un error'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Lista de Categorías'
        context['create_url'] = reverse_lazy('erp:category_create')
        context['list_url'] = reverse_lazy('erp:category_list')
        context['entity'] = 'Categorías'
        context['action_entity'] = ''
        return context


class CategoryDetailView(LoginRequiredMixin, DetailView):
    model = Categorias
    template_name = 'pages/category/category_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Detalle de Categoría'
        context['entity'] = 'Categorías'
        context['action_entity'] = 'Detalle'
        context['list_url'] = reverse_lazy('erp:category_list')

        return context


class CategoryCreateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, CreateView):
    model = Categorias
    form_class = CategoriasForm
    template_name = 'pages/category/category_create.html'
    success_url = reverse_lazy('erp:category_list')
    permission_required = 'ColombraroERP.add_categorias'
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'create':
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Crear Nueva Categoría'
        context['entity'] = 'Categorías'
        context['action_entity'] = 'Crear'
        context['list_url'] = reverse_lazy('erp:category_list')
        context['action'] = 'create'
        return context


class CategoryUpdateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    model = Categorias
    form_class = CategoriasForm
    template_name = 'pages/category/category_create.html'
    success_url = reverse_lazy('erp:category_list')
    permission_required = 'ColombraroERP.change_categorias'
    url_redirect = success_url

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'update':
                # La variable form obtiene los datos del formulario.
                # Esta opción es mejor usarla ya que obtiene imagenes a diferencia de: form = CategoriasForm(request.POST)
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Categoría'
        context['entity'] = 'Categorías'
        context['action_entity'] = 'Editar'
        context['list_url'] = reverse_lazy('erp:category_list')
        context['action'] = 'update'
        return context


class CategoryDeleteView(LoginRequiredMixin, ValidatePermissionRequiredMixin, DeleteView):
    model = Categorias
    template_name = 'pages/category/category_delete.html'
    success_url = reverse_lazy('erp:category_list')
    permission_required = 'ColombraroERP.delete_categorias'
    url_redirect = success_url

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['prop'] = self.object.nombre
        context['title'] = 'Eliminar Categoría'
        context['entity'] = 'Categorías'
        context['action_entity'] = 'Eliminar'
        context['list_url'] = reverse_lazy('erp:category_list')
        return context

ColombraroERP/views/client/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.http import JsonResponse
# Mixines
from ColombraroERP.mixins import IsSuperUserMixins, ValidatePermissionRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin
# Decoradores
from django.views.decorators.csrf import csrf_exempt
# Listas basadas en Clases
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
# Clientes
from ColombraroERP.models import Clientes
from ColombraroERP.forms import ClientesForm


class ClientListView(LoginRequiredMixin, ListView):
    model = Clientes
    template_name = 'pages/client/client_list.html'

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        print(request)
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'searchdata':
                data = []
                for i in Clientes.objects.all():
                    data.append(i.toJSON())
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data, safe=False)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Listado de Clientes'
        context['create_url'] = reverse_lazy('erp:client_create')
        context['list_url'] = reverse_lazy('erp:client_list')
        context['entity'] = 'Clientes'
        context['action_entity'] = ''
        return context

class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Clientes
    template_name = 'pages/client/client_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Detalle de Cliente'
        context['entity'] = 'Cliente'
        context['action_entity'] = 'Detalle'
        context['list_url'] = reverse_lazy('erp:client_list')
        return context

class ClientCreateView(LoginRequiredMixin,CreateView):
    model = Clientes
    form_class = ClientesForm
    template_name = 'pages/client/client_create.html'
    success_url = reverse_lazy('erp:client_list')


    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'create':
                form = self.get_form()
                data = form.save()
            else:
                # Usando AJAX
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Crear nuevo Cliente'
        context['entity'] = 'Clientes'
        context['action_entity'] = 'Crear'
        context['list_url'] = reverse_lazy('erp:client_list')
        context['action'] = 'create'
        return context

class ClientUpdateView(LoginRequiredMixin,UpdateView):
    model = Clientes
    form_class = ClientesForm
    template_name = 'pages/client/client_create.html'
    success_url = reverse_lazy('erp:client_list')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'update':
                # La variable form obtiene los datos del formulario.
                # Esta opción es mejor usarla ya que obtiene imagenes a diferencia de: form = CategoriasForm(request.POST)
                form = self.get_form()
                data = form.save()
            else:
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Editar Cliente'
        context['entity'] = 'Clientes'
        context['action_entity'] = 'Editar'
        context['list_url'] = reverse_lazy('erp:client_list')
        context['action'] = 'update'
        return context

class ClientDeleteView(LoginRequiredMixin,DeleteView):
    model = Clientes
    template_name = 'pages/client/client_delete.html'
    success_url = reverse_lazy('erp:client_list')

    @csrf_exempt
    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            self.object.delete()
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['prop'] = self.object.nombre + ' ' + self.object.apellido
        context['title'] = 'Eliminar Cliente'
        context['entity'] = 'Clientes'
        context['action_entity'] = 'Eliminar'
        context['list_url'] = reverse_lazy('erp:client_list')
        return context

ColombraroERP/views/sale.py/views.py
from django.urls import reverse_lazy
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
# Decoradores
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# Listas basadas en Clases
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
# Categorias
from ColombraroERP.models import Ventas
from ColombraroERP.forms import VentasForm


class VentasCreateView(CreateView):
    model = Ventas
    form_class = VentasForm
    template_name = 'pages/category/category_create.html'
    success_url = reverse_lazy('erp:category_list')

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *arg, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'create':
                # La variable form obtiene los datos del formulario.
                # Esta opción es mejor usarla ya que obtiene imagenes a diferencia de: form = CategoriasForm(request.POST)
                form = self.get_form()
                data = form.save()
            else:
                # Usando AJAX
                data['error'] = 'No ha ingresado a ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return JsonResponse(data)

        # Antes de usar AJAX
        #     return HttpResponseRedirect(self.success_url)
        # self.object = None
        # context = self.get_context_data(**kwargs)
        # context['form'] = form
        # return render(request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Crear nueva Categoría'
        context['entity'] = 'Categorías'
        context['list_url'] = reverse_lazy('erp:category_list')
        context['action'] = 'create'
        return context

ColombraroERP/templates/components/body.html
{% extends 'components/head.html' %} {% block body %}
<body class="bg-light">
  <div class="wrapper">
    <!-- Sidebar -->
    {% include 'components/sidebar.html' %}
    <!-- Header -->
    {% include 'components/navbar.html' %}

    <!-- Content -->
    <div class="content-wrapper">
      <div class="content-header">
        <div class="container bg-white p-2">
          <div class="row">
            <div class="col-sm-12">
              <ol class="breadcrumb float-sm-left">
                <li class="breadcrumb-item">
                  <a href="{% url 'erp:dashboard' %}">
                    <i class="fa fa-home" aria-hidden="true"></i>
                    Panel</a
                  >
                </li>
                <li class="breadcrumb-item">
                  <a href="{{list_url}}">{{entity }}</a>
                </li>
                {% if action_entity != '' %}
                <li class="breadcrumb-item">
                  <a href="#">{{action_entity}}</a>
                </li>
                {% endif%}
              </ol>
            </div>
          </div>
        </div>
      </div>
      <div class="content">
        <div class="row">
            <div class="col-lg-12">
                <!--  ---------- Content -------- -->
              {% block content %} 
              
              {% endblock %}
            </div>
        </div>
      </div>
    </div>
    <!-- Footer -->
    {% include 'components/footer.html' %}
  </div>
  <!--Block JavaScript para Datable-->
  {% block javaScript %} {% endblock %}
  <script>
    {% if messages %}
        var html = '<p>';
        {% for message in messages %}
            html += '{{ message }}<br>';
        {% endfor %}
        html += '</p>';
        Swal.fire({
            title: 'Info!',
            html: html,
            icon: 'info'
        });
    {% endif %}
  </script>
</body>

{% endblock %}

ColombraroERP/templates/components/dashboard.html
{% extends 'components/body.html' %} {% load static %} {% block head %}
<script src="{% static 'lib/highcharts/highcharts.js' %}"></script>
<script src="{% static 'lib/highcharts/modules/exporting.js' %}"></script>
<script src="{% static 'lib/highcharts/modules/export-data.js' %}"></script>
<script src="{% static 'lib/highcharts/modules/accessibility.js' %}"></script>
{% endblock %} {% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <div id="container"></div>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-lg-12">
      <div id="container-pie"></div>
    </div>
  </div>
  <br />
</div>
<script type="application/javascript">
  var graphcolumn = Highcharts.chart("container", {
    chart: {
      type: "column",
    },
    title: {
      text: "Reportes Anual de Ventas",
    },
    subtitle: {
      text: "Año 2023",
    },
    xAxis: {
      categories: [
        "Enero",
        "Febrero",
        "Marzo",
        "Abril",
        "Mayo",
        "Junio",
        "Julio",
        "Agosto",
        "Septiembre",
        "Octubre",
        "Noviembre",
        "Deciembre",
      ],
      crosshair: true,
    },
    yAxis: {
      min: 0,
      title: {
        text: "Vendido en TOTAL $",
      },
    },
    tooltip: {
      headerFormat: '<span style="font-size:51px">{point.key}</span><table>',
      pointFormat:
        '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
        '<td style="padding:0"><b>${point.y:.1f}</b></td></tr>',
      footerFormat: "</table>",
      shared: true,
      useHTML: true,
    },
    plotOptions: {
      column: {
        pointPadding: 0.2,
        borderWidth: 0,
      },
    },
  });
  //-------------------GRAFICO TORTA ------------------------------
  var graphpie = Highcharts.chart("container-pie", {
    chart: {
      plotBackgroundColor: null,
      plotBorderWidth: null,
      plotShadow: false,
      type: "pie",
    },
    title: {
      text: "Porcentaje de Productos más Vendidos",
    },
    tooltip: {
      pointFormat: "{series.name}: <b>{point.percentage:.1f}%</b>",
    },
    accessibility: {
      point: {
        valueSuffix: "%",
      },
    },
    plotOptions: {
      pie: {
        allowPointSelect: true,
        cursor: "pointer",
        dataLabels: {
          enabled: true,
          format: "<b>{point.name}</b>: {point.percentage:.1f} %",
        },
      },
    },
  });

  function get_grafico_ventas_anual() {
    $.ajax({
      url: window.location.pathname, //window.location.pathname
      type: "POST",
      data: {
        action: "get_grafico_ventas_anual",
      },
      dataType: "json",
    })
      .done(function (data) {
        if (!data.hasOwnProperty("error")) {
          graphcolumn.addSeries(data);
          return false;
        }
        message_error(data.error);
      })
      .fail(function (jqXHR, textStatus, errorThrown) {
        alert(textStatus + ": " + errorThrown);
      })
      .always(function (data) {});
  }

  function get_grafico_productos_vendidos() {
    $.ajax({
      url: window.location.pathname, //window.location.pathname
      type: "POST",
      data: {
        action: "get_grafico_productos_vendidos",
      },
      dataType: "json",
    })
      .done(function (data) {
        if (!data.hasOwnProperty("error")) {
          graphpie.addSeries(data);
          return false;
        }
        message_error(data.error);
      })
      .fail(function (jqXHR, textStatus, errorThrown) {
        alert(textStatus + ": " + errorThrown);
      })
      .always(function (data) {});
  }

  $(function () {
    get_grafico_ventas_anual();
    get_grafico_productos_vendidos();
  });
</script>

{% endblock %}

ColombraroERP/templates/components/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline"><b>Versión</b> 1.0.1.5</div>
  <!-- Default to the left -->
  <strong
    >Copyright &copy; 2022-2023
    <a href="https://www.linkedin.com/in/cantarini-maria-sol/" target="_blank"
      >María Sol Cantarini</a
    >.
  </strong>
  All rights reserved.
</footer>

ColombraroERP/templates/components/navbar.html
<nav
  class="main-header navbar navbar-expand navbar-dark"
  style="background-color: #eb1d36; border: 1px #eb1d36"
>
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"
        ><i class="fas fa-bars"></i
      ></a>
    </li>
  </ul>
  <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="fas fa-users-cog"></i> {{request.user.username}}
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        {% if request.user.last_login is not None %}
        <p class="dropdown-header" style="font-size: 20px">
          <b>Último Acceso</b> <br />
          <span>{{request.user.last_login}}</span>
        </p>
        <div class="dropdown-divider"></div>
        {% endif %}
        <a
          href="{% url 'user:user_detail' request.user.id %}"
          class="dropdown-item"
        >
          <i class="fas fa-user mr-2"></i> Ver Perfil
        </a>
        <div class="dropdown-divider"></div>
        {% if user.is_superuser %}
        <a
          href="{% url 'user:user_update' request.user.id %}"
          class="dropdown-item"
        >
          <i class="fas fa-edit mr-2"></i> Editar perfil
        </a>
        {% endif %}
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}">
        <i class="fas fa-power-off" aria-hidden="true"></i>
      </a>
    </li>
  </ul>
</nav>

ColombraroERP/templates/components/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4 bg-dark">
  <div class="brand-link">
    <img
      src="{% static 'img/logo/colombraro-logo.png' %}"
      alt="Colombraro Logo"
      class="brand-image elevation-2 mx-5"
      style="width: 85px; border-radius: 34%"
    />
    <br />
    <span class="text-light p-3"><b>Colombraro ERP</b></span>
  </div>
  <div class="sidebar">
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img
          src="{{request.user.get_imagen}}"
          class="img-circle elevation-2 bg-light p-1"
          alt="Imagen de Usuario"
        />
      </div>
      <div class="info">
        {% if request.user.first_name == '' or request.user.last_name == '' %}
        <span class="d-block text-light">{{request.user.username}}</span>
        {% else %}
        <span class="d-block text-light">{{request.user.get_full_name}}</span>
        {% endif %}
      </div>
    </div>
    <nav class="mt-2" id="nav-sidebar">
      <ul
        class="nav nav-pills nav-sidebar flex-column"
        data-widget="treeview"
        role="menu"
        data-accordion="false"
      >
        <li class="nav-item">
          <a
            href="{% url 'erp:dashboard' %}"
            class="nav-link {% if request.path == '/erp/home/' %}active{% endif %}"
          >
            <i class="fa fa-home"></i>
            <p>Panel</p>
          </a>
        </li>
        <li class="nav-item">
          <a
            href="{% url 'erp:category_list' %}"
            class="nav-link {% if request.path == '/erp/category/list/' %}active {% endif %}"
          >
            <i class="nav-icon fas fa-truck-loading"></i>
            <p>Categorías</p>
          </a>
        </li>
        <li class="nav-item">
          <a
            href="{% url 'erp:product_list' %}"
            class="nav-link {% if request.path == '/erp/product/list/' %}active{% endif %}"
          >
            <i class="nav-icon fas fa-boxes"></i>
            <p>Productos</p>
          </a>
        </li>
        <li class="nav-item">
          <a
            href="{% url 'erp:client_list' %}"
            class="nav-link {% if request.path == '/erp/client/list/' %}active{% endif %}"
          >
            <i class="nav-icon fas fa-users"></i>
            <p>Clientes</p>
          </a>
        </li>
        <li class="nav-item">
          <a
            href="{% url 'erp:sale_list' %}"
            class="nav-link {% if request.path == '/erp/sale/list/' %}active{% endif %}"
          >
            <i class="nav-icon fas fa-shopping-cart"></i>
            <p>Ventas</p>
          </a>
        </li>
        <li class="nav-item">
          <a
            href="{% url 'user:user_list' %}"
            class="nav-link {% if request.path == '/user/list/' %}active{% endif %}"
          >
            <i class="nav-icon fas fa-user-friends"></i>
            <p>Usuarios</p>
          </a>
        </li>
        {% if user.is_superuser %}
        <li
          class="nav-item {% if request.path == '/reports/sale/' %}menu-open{% endif %}"
        >
          <a href="#" class="nav-link">
            <i class="fas fa-chart-bar"></i>
            <p>
              Reportes
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a
                href="{% url 'reports:reports_sale' %}"
                class="nav-link {% if request.path == '/reports/sale/' %}active{% endif %}"
              >
                <p>
                  <i class="nav-icon far fa-circle"></i>
                  Ventas
                </p>
              </a>
            </li>
          </ul>
        </li>
        {% endif %}
      </ul>
    </nav>
  </div>
</aside>